# Generated by Django 3.2 on 2025-01-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0004_alter_resetpasswordtoken_user_agent'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPasswordResetToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_rest_passwordreset.resetpasswordtoken',),
        ),
    ]
