# Generated by Django 3.2 on 2024-12-14 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('rental', 'Rental'), ('purchase', 'Purchase')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented')], max_length=50)),
                ('cover_image', models.ImageField(upload_to='elbis/cover_images/')),
                ('bedroom_image', models.ImageField(upload_to='elbis/bedroom_images/')),
                ('bathroom_image', models.ImageField(upload_to='elbis/bathroom_images/')),
                ('video_url', models.URLField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
